/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageexplorer;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.LinkedList;

/**
 *
 * @author crazm_000
 */
public interface HtmlBuilderInterface {
	/**
	 * This method builds all the required web pages and files from the given
	 * Package list
	 * 
	 * @param packages is an ArrayList of packages, each containing information for
	 *                 the web page
	 */
	public void buildAllHtmlPages(ArrayList<Package> packages);

	/**
	 * This method builds one .html page from given package
	 * 
	 * @param pack is a single Package data structure, from which information is
	 *             extracted
	 */
	public void buildPackagePage(Package pack);

	/**
	 * This method creates file and writes the htmlCodeLines LinkedList inside it
	 * 
	 * @param htmlCodeLines this is the list of html code lines to be written into a
	 *                      file
	 * @param pageName      name of the web page or file as String
	 */
	public void writeHtmlFile(LinkedList<String> htmlCodeLines, String pageName);

	/**
	 * This method generates a html filename from the given string
	 * 
	 * @param pageName the page name that will get an .html extension
	 * @return is the filename as a String
	 */
	public String generateHtmlFileName(String pageName);

	/**
	 * This method opens the index.html file in a default browser that has been
	 * generated by the program.
	 * 
	 * @throws IOException        empty paths generate null IOException
	 * @throws URISyntaxException certain letters can cause error
	 */
	public void openIndexPageWithBrowser() throws URISyntaxException, IOException;

	/**
	 * This method checks if the user is using a Debian based OS. This is required,
	 * because folder path information has different syntax
	 * 
	 * @return true if current operating system is debian. The address starts with
	 *         "/" instead of "C:\etc"
	 */
	public boolean isOperatingSystemDebian();

}
